# Form implementation generated from reading ui file 'OSASettings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OSASettings(object):
    def setupUi(self, OSASettings):
        OSASettings.setObjectName("OSASettings")
        OSASettings.resize(500, 400)
        OSASettings.setWindowTitle("")
        self.cancelButton = QtWidgets.QPushButton(parent=OSASettings)
        self.cancelButton.setGeometry(QtCore.QRect(410, 360, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.applyButton = QtWidgets.QPushButton(parent=OSASettings)
        self.applyButton.setGeometry(QtCore.QRect(320, 360, 75, 23))
        self.applyButton.setObjectName("applyButton")
        self.okButton = QtWidgets.QPushButton(parent=OSASettings)
        self.okButton.setGeometry(QtCore.QRect(230, 360, 75, 23))
        self.okButton.setObjectName("okButton")
        self.groupBox = QtWidgets.QGroupBox(parent=OSASettings)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 161, 111))
        self.groupBox.setObjectName("groupBox")
        self.lambdaStartEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lambdaStartEdit.setGeometry(QtCore.QRect(70, 30, 71, 20))
        self.lambdaStartEdit.setObjectName("lambdaStartEdit")
        self.lambdaStopEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lambdaStopEdit.setGeometry(QtCore.QRect(70, 70, 71, 20))
        self.lambdaStopEdit.setObjectName("lambdaStopEdit")
        self.lambdaStartLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.lambdaStartLabel.setGeometry(QtCore.QRect(20, 30, 51, 21))
        self.lambdaStartLabel.setObjectName("lambdaStartLabel")
        self.lambdaStopLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.lambdaStopLabel.setGeometry(QtCore.QRect(20, 70, 51, 21))
        self.lambdaStopLabel.setObjectName("lambdaStopLabel")
        self.resolutionEdit = QtWidgets.QLineEdit(parent=OSASettings)
        self.resolutionEdit.setGeometry(QtCore.QRect(100, 190, 41, 20))
        self.resolutionEdit.setObjectName("resolutionEdit")
        self.resolutionLabel = QtWidgets.QLabel(parent=OSASettings)
        self.resolutionLabel.setGeometry(QtCore.QRect(30, 190, 61, 21))
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.autoScalingCheck = QtWidgets.QCheckBox(parent=OSASettings)
        self.autoScalingCheck.setGeometry(QtCore.QRect(20, 270, 91, 20))
        self.autoScalingCheck.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.autoScalingCheck.setObjectName("autoScalingCheck")
        self.osaConnectedLabel = QtWidgets.QLabel(parent=OSASettings)
        self.osaConnectedLabel.setGeometry(QtCore.QRect(30, 20, 181, 16))
        self.osaConnectedLabel.setObjectName("osaConnectedLabel")
        self.nmLabel = QtWidgets.QLabel(parent=OSASettings)
        self.nmLabel.setGeometry(QtCore.QRect(150, 190, 47, 21))
        self.nmLabel.setObjectName("nmLabel")
        self.averagingEdit = QtWidgets.QLineEdit(parent=OSASettings)
        self.averagingEdit.setGeometry(QtCore.QRect(100, 230, 41, 20))
        self.averagingEdit.setObjectName("averagingEdit")
        self.averagingLabel = QtWidgets.QLabel(parent=OSASettings)
        self.averagingLabel.setGeometry(QtCore.QRect(30, 230, 61, 21))
        self.averagingLabel.setObjectName("averagingLabel")
        self.cancelButton.raise_()
        self.applyButton.raise_()
        self.okButton.raise_()
        self.groupBox.raise_()
        self.resolutionEdit.raise_()
        self.autoScalingCheck.raise_()
        self.osaConnectedLabel.raise_()
        self.resolutionLabel.raise_()
        self.nmLabel.raise_()
        self.averagingEdit.raise_()
        self.averagingLabel.raise_()

        self.retranslateUi(OSASettings)
        QtCore.QMetaObject.connectSlotsByName(OSASettings)

    def retranslateUi(self, OSASettings):
        _translate = QtCore.QCoreApplication.translate
        self.cancelButton.setText(_translate("OSASettings", "Cancel"))
        self.applyButton.setText(_translate("OSASettings", "Apply"))
        self.okButton.setText(_translate("OSASettings", "Ok"))
        self.groupBox.setTitle(_translate("OSASettings", "Wavelength Range"))
        self.lambdaStartLabel.setText(_translate("OSASettings", "λ start:"))
        self.lambdaStopLabel.setText(_translate("OSASettings", "λ stop:"))
        self.resolutionLabel.setText(_translate("OSASettings", "Resolution:"))
        self.autoScalingCheck.setText(_translate("OSASettings", "Auto Scaling"))
        self.osaConnectedLabel.setText(_translate("OSASettings", "OSA not connected"))
        self.nmLabel.setText(_translate("OSASettings", "nm"))
        self.averagingLabel.setText(_translate("OSASettings", "Averaging"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OSASettings = QtWidgets.QWidget()
    ui = Ui_OSASettings()
    ui.setupUi(OSASettings)
    OSASettings.show()
    sys.exit(app.exec())
